server:
  port: 8001

spring:
  application:
    name: payment-service
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:paymentdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    topic:
      payment: orders
    listener:
      ack-mode: MANUAL_IMMEDIATE
    bootstrap-servers: kafka-broker:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'